In [1]:
from pyspark.sql import SparkSession

spark = (
    SparkSession.builder
    .appName("dimensions_check")
    .config("spark.hadoop.fs.s3a.endpoint", "http://minio:9000")
    .config("spark.hadoop.fs.s3a.access.key", "admin")
    .config("spark.hadoop.fs.s3a.secret.key", "admin123")
    .config("spark.hadoop.fs.s3a.path.style.access", "true")
    .config("spark.hadoop.fs.s3a.connection.ssl.enabled", "false")
    .config("spark.hadoop.fs.s3a.impl", "org.apache.hadoop.fs.s3a.S3AFileSystem")
    .getOrCreate()
)

In [2]:
dim_date = spark.read.parquet("s3a://gold/dimensions/dim_date/")

In [3]:
dim_date.toPandas()

     date_key   full_date  day  month  quarter  year day_of_week  is_weekend
0    20091201  2009-12-01    1     12        4  2009     Tuesday       False
1    20091202  2009-12-02    2     12        4  2009   Wednesday       False
2    20091203  2009-12-03    3     12        4  2009    Thursday       False
3    20091204  2009-12-04    4     12        4  2009      Friday       False
4    20091205  2009-12-05    5     12        4  2009    Saturday        True
..        ...         ...  ...    ...      ...   ...         ...         ...
369  20101205  2010-12-05    5     12        4  2010      Sunday        True
370  20101206  2010-12-06    6     12        4  2010      Monday       False
371  20101207  2010-12-07    7     12        4  2010     Tuesday       False
372  20101208  2010-12-08    8     12        4  2010   Wednesday       False
373  20101209  2010-12-09    9     12        4  2010    Thursday       False

[374 rows x 8 columns]

In [4]:
dim_customer = spark.read.parquet("s3a://gold/dimensions/dim_customer/")

In [5]:
dim_customer.toPandas()

,customer_id,country,first_seen_time,first_seen_year,cohort
0,12346,United Kingdom,2009-12-14 08:34:00,2009,cohort_2009
1,12347,Iceland,2010-10-31 14:20:00,2010,cohort_2010
2,12348,Finland,2010-09-27 14:59:00,2010,cohort_2010
3,12349,Italy,2009-12-04 12:49:00,2009,cohort_2009
4,12351,Unspecified,2010-11-29 15:23:00,2010,cohort_2010
...,...,...,...,...,...
4377,18283,United Kingdom,2010-02-19 17:16:00,2010,cohort_2010
4378,18284,United Kingdom,2010-10-04 11:33:00,2010,cohort_2010
4379,18285,United Kingdom,2010-02-17 10:24:00,2010,cohort_2010
4380,18286,United Kingdom,2009-12-16 10:45:00,2009,cohort_2009
4381,18287,United Kingdom,2009-12-01 14:19:00,2009,cohort_2009

In [6]:
dim_pdt = spark.read.parquet("s3a://gold/dimensions/dim_product/")

In [7]:
dim_pdt.toPandas()

        stock_code                         description
0            10002         INFLATABLE POLITICAL GLOBE
1           10002R               ROBOT PENCIL SHARPNER
2            10080            GROOVY CACTUS INFLATABLE
3            10109                BENDY COLOUR PENCILS
4            10120                        DOGGY RUBBER
...            ...                                 ...
4271  gift_0001_40  Dotcomgiftshop Gift Voucher £40.00
4272  gift_0001_50  Dotcomgiftshop Gift Voucher £50.00
4273  gift_0001_70  Dotcomgiftshop Gift Voucher £70.00
4274  gift_0001_80  Dotcomgiftshop Gift Voucher £80.00
4275             m                              Manual

[4276 rows x 2 columns]

In [8]:
dim_geo = spark.read.parquet("s3a://gold/dimensions/dim_geography/")

In [9]:
dim_geo.toPandas()

                 country
0                 Sweden
1                Germany
2                    RSA
3                 France
4                 Greece
5                Belgium
6                Finland
7            Unspecified
8                  Italy
9                   EIRE
10             Lithuania
11                Norway
12                 Spain
13               Denmark
14                Israel
15       Channel Islands
16                   USA
17                Cyprus
18           Switzerland
19  United Arab Emirates
20                Canada
21                 Japan
22                Poland
23              Portugal
24             Australia
25               Austria
26                 Korea
27        United Kingdom
28           Netherlands
29               Iceland
30               Lebanon
31               Bahrain
32               Nigeria
33             Singapore
34                Brazil
35              Thailand
36             Hong Kong
37               Bermuda
38                 Malta
39           West Indies

In [10]:
fact_order_items = spark.read.parquet("s3a://gold/facts/fact_order_items/")

In [11]:
fact_order_items.toPandas()

,invoice_id,stock_code,customer_id,country,date_key,quantity,unit_price,total_amount,is_cancelled,event_time,kafka_timestamp,bronze_ingestion_time,silver_ingestion_time,year,month
0,529997,22959,15312,United Kingdom,20101101,25,0.42,10.50,False,2010-11-01 08:58:00,2026-04-08 06:49:12.380,2026-04-08 06:49:12.476,2026-04-25 10:04:05.481821,2010,11
1,530000,21257,None,United Kingdom,20101101,1,16.13,16.13,False,2010-11-01 09:13:00,2026-04-08 06:49:15.474,2026-04-08 06:49:16.277,2026-04-25 10:04:05.481821,2010,11
2,530000,22659,None,United Kingdom,20101101,2,2.51,5.02,False,2010-11-01 09:13:00,2026-04-08 06:49:15.465,2026-04-08 06:49:16.277,2026-04-25 10:04:05.481821,2010,11
3,530000,35400,None,United Kingdom,20101101,1,16.98,16.98,False,2010-11-01 09:13:00,2026-04-08 06:49:15.464,2026-04-08 06:49:16.277,2026-04-25 10:04:05.481821,2010,11
4,530001,21259,None,United Kingdom,20101101,2,12.72,25.44,False,2010-11-01 09:13:00,2026-04-08 06:49:15.394,2026-04-08 06:49:15.429,2026-04-25 10:04:05.481821,2010,11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
518441,C537856,37370,14388,United Kingdom,20101208,2,1.25,2.50,True,2010-12-08 15:59:00,2026-04-08 07:48:13.132,2026-04-08 07:48:13.277,2026-04-25 10:04:05.481821,2010,12
518442,C537860,20675,16252,United Kingdom,20101208,8,1.25,10.00,True,2010-12-08 16:15:00,2026-04-08 07:48:16.849,2026-04-08 07:48:17.082,2026-04-25 10:04:05.481821,2010,12
518443,C537860,20676,16252,United Kingdom,20101208,8,1.25,10.00,True,2010-12-08 16:15:00,2026-04-08 07:48:16.832,2026-04-08 07:48:17.082,2026-04-25 10:04:05.481821,2010,12
518444,C538059,20914,14205,United Kingdom,20101209,6,2.95,17.70,True,2010-12-09 13:38:00,2026-04-08 07:49:21.710,2026-04-08 07:49:22.081,2026-04-25 10:04:05.481821,2010,12
518445,C538059,22727,14205,United Kingdom,20101209,4,3.75,15.00,True,2010-12-09 13:38:00,2026-04-08 07:49:21.710,2026-04-08 07:49:22.081,2026-04-25 10:04:05.481821,2010,12

In [14]:
revenue_by_country_month = spark.read.parquet("s3a://gold/revenue_sales/revenue_by_country_month/")

In [16]:
revenue_by_country_month.toPandas()

,country,year,month,total_revenue,total_line_items,total_units_sold,year_month
0,Australia,2009,12,271.10,14,160,2009-12
1,Australia,2010,2,1029.66,32,624,2010-02
2,Australia,2010,3,429.39,19,191,2010-03
3,Australia,2010,4,630.95,17,560,2010-04
4,Australia,2010,5,2371.15,59,667,2010-05
...,...,...,...,...,...,...,...
284,Unspecified,2010,4,252.52,14,153,2010-04
285,Unspecified,2010,7,2379.88,68,1276,2010-07
286,Unspecified,2010,9,1978.15,110,1256,2010-09
287,Unspecified,2010,11,540.57,50,367,2010-11
288,West Indies,2010,8,536.41,54,395,2010-08

In [17]:
top_pdts = spark.read.parquet("s3a://gold/revenue_sales/top_products_global/")

In [18]:
top_pdts.toPandas()

,stock_code,description,total_revenue,total_units_sold,total_line_items,revenue_rank,units_rank
0,M,Manual,262865.49,2737,539,1,529
1,22423,REGENCY CAKESTAND 3 TIER,169724.81,13674,2034,2,59
2,85123A,WHITE HANGING HEART T-LIGHT HOLDER,158276.22,58377,3375,3,2
3,B,Adjust bad debt,136552.02,3,3,4,1898
4,DOT,DOTCOM POSTAGE,116408.71,1233,734,5,970
...,...,...,...,...,...,...,...
4312,85098A,None,0.00,1,1,4013,1900
4313,79309A,None,0.00,1,1,4013,1900
4314,84811A,None,0.00,1,1,4013,1900
4315,72778,None,0.00,1,1,4013,1900
4316,22213,None,0.00,1,1,4013,1900

In [19]:
clv = spark.read.parquet("s3a://gold/customer_analytics/customer_lifetime_value/")

In [20]:
clv.toPandas()

,customer_id_clean,lifetime_revenue,total_orders,avg_line_item_value,total_units_purchased,first_order_date,last_order_date,avg_order_value,clv_rank
0,guest,1609930.95,2889,15.29,472044,2009-12-01 11:49:00,2010-12-09 17:18:00,557.26,1
1,18102,349164.35,89,556.88,124216,2009-12-01 09:24:00,2010-12-09 13:44:00,3923.19,2
2,14646,248396.50,78,140.02,170342,2009-12-02 16:52:00,2010-11-30 16:28:00,3184.57,3
3,14156,196549.74,102,74.28,108105,2009-12-01 12:30:00,2010-12-03 11:48:00,1926.96,4
4,14911,152121.22,205,27.32,69709,2009-12-01 11:41:00,2010-12-09 12:17:00,742.05,5
...,...,...,...,...,...,...,...,...,...
4310,15913,6.30,1,6.30,3,2010-06-23 16:31:00,2010-06-23 16:31:00,6.30,4235
4311,13788,3.75,1,3.75,1,2010-07-22 15:50:00,2010-07-22 15:50:00,3.75,4236
4312,14095,2.95,1,2.95,1,2009-12-17 12:49:00,2009-12-17 12:49:00,2.95,4237
4313,14827,0.00,1,0.00,5,2010-02-12 15:47:00,2010-02-12 15:47:00,0.00,4238
4314,14103,0.00,1,0.00,5,2010-02-12 14:58:00,2010-02-12 14:58:00,0.00,4238

In [21]:
new_vs_ret = spark.read.parquet("s3a://gold/customer_analytics/new_vs_returning/")

In [22]:
new_vs_ret.toPandas()

    year  month customer_type  customer_count year_month
0   2009     12           new             955    2009-12
1   2010      1           new             383    2010-01
2   2010      1     returning             337    2010-01
3   2010      2           new             376    2010-02
4   2010      2     returning             398    2010-02
5   2010      3           new             443    2010-03
6   2010      3     returning             614    2010-03
7   2010      4           new             294    2010-04
8   2010      4     returning             648    2010-04
9   2010      5           new             254    2010-05
10  2010      5     returning             712    2010-05
11  2010      6           new             270    2010-06
12  2010      6     returning             771    2010-06
13  2010      7           new             186    2010-07
14  2010      7     returning             742    2010-07
15  2010      8           new             162    2010-08
16  2010      8     returning             747    2010-08
17  2010      9           new             243    2010-09
18  2010      9     returning             902    2010-09
19  2010     10           new             377    2010-10
20  2010     10     returning            1120    2010-10
21  2010     11           new             325    2010-11
22  2010     11     returning            1282    2010-11
23  2010     12           new              46    2010-12
24  2010     12     returning             527    2010-12

In [23]:
rr = spark.read.parquet("s3a://gold/customer_analytics/retention_rate/")

In [24]:
rr.toPandas()

,year,month,active_customers,retained_next_month,retention_rate_pct,year_month
0,2009,12,955,337,35.29,2009-12
1,2010,1,720,262,36.39,2010-01
2,2010,2,774,314,40.57,2010-02
3,2010,3,1057,378,35.76,2010-03
4,2010,4,942,345,36.62,2010-04
5,2010,5,966,368,38.10,2010-05
6,2010,6,1041,392,37.66,2010-06
7,2010,7,928,350,37.72,2010-07
8,2010,8,909,364,40.04,2010-08
9,2010,9,1145,463,40.44,2010-09
10,2010,10,1497,657,43.89,2010-10
11,2010,11,1607,346,21.53,2010-11
12,2010,12,573,0,0.00,2010-12

In [26]:
tcbp = spark.read.parquet("s3a://gold/customer_analytics/top_customers_by_orders/")

In [27]:
tcbp.toPandas()

,customer_id,total_orders,total_revenue,first_order_date,last_order_date,country,cohort,order_rank
0,14911,205,152121.22,2009-12-01 11:41:00,2010-12-09 12:17:00,EIRE,cohort_2009,1
1,17850,155,51208.87,2009-12-05 12:28:00,2010-12-02 15:27:00,United Kingdom,cohort_2009,2
2,12748,144,22421.65,2009-12-04 17:31:00,2010-12-09 13:22:00,United Kingdom,cohort_2009,3
3,15311,121,55942.74,2009-12-01 11:21:00,2010-12-09 14:15:00,United Kingdom,cohort_2009,4
4,13089,109,57885.45,2009-12-02 15:44:00,2010-12-06 14:00:00,United Kingdom,cohort_2009,5
...,...,...,...,...,...,...,...,...
4309,17195,1,562.98,2010-02-22 13:05:00,2010-02-22 13:05:00,United Kingdom,cohort_2010,64
4310,14254,1,601.03,2010-10-03 11:52:00,2010-10-03 11:52:00,United Kingdom,cohort_2010,64
4311,15337,1,373.02,2010-10-24 15:29:00,2010-10-24 15:29:00,United Kingdom,cohort_2010,64
4312,15558,1,202.68,2010-03-10 15:25:00,2010-03-10 15:25:00,United Kingdom,cohort_2010,64
4313,17993,1,225.99,2010-04-01 14:23:00,2010-04-01 14:23:00,United Kingdom,cohort_2010,64